name: Python

on: ["pull_request"]

jobs:
  python:
    name: Check Python build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          cd integrations/snake
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          args: --release -i python3.10 -b pyo3 -m integrations/snake/Cargo.toml --out dist

      - name: Run Example
        run: |
          pip3 install snake --no-index --find-links dist/ --force-reinstall
          cd integrations/snake
          python backtest/test.py
